### PR TITLE
correct spelling mistake.

### PR DESCRIPTION
**Pull request by iiio2**

### CODE REVIEW

**Comment by brillout** [comment]
Thanks! I've just added `.prettierrc`, can you apply it to your changes?

**Comment by iiio2** [comment]
@brillout i have added.

**Comment by brillout** [comment]
It doesn't seem to have applied to the HTML?

**Comment by iiio2** [comment]
@brillout but i have added it.

**Comment by iiio2** [comment]
@brillout thank you :)

**Pull request merged**
